/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'

// Create Virtual Routes

const SignLazyImport = createFileRoute('/sign')()
const DashboardIndexLazyImport = createFileRoute('/_dashboard/')()
const DashboardAccountLazyImport = createFileRoute('/_dashboard/account')()

// Create/Update Routes

const SignLazyRoute = SignLazyImport.update({
  path: '/sign',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign.lazy').then((d) => d.Route))

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/index.lazy').then((d) => d.Route),
)

const DashboardAccountLazyRoute = DashboardAccountLazyImport.update({
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/account.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/sign': {
      preLoaderRoute: typeof SignLazyImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/account': {
      preLoaderRoute: typeof DashboardAccountLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/': {
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DashboardRoute.addChildren([
    DashboardAccountLazyRoute,
    DashboardIndexLazyRoute,
  ]),
  SignLazyRoute,
])

/* prettier-ignore-end */
